#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: auth-depl
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: auth
#  template:
#    metadata:
#      labels:
#        app: auth
#    spec:
#      containers:
#        - name: auth
#          image: us.gcr.io/easymez/auth
#          env:
#            - name: MONGO_URI
#              value: "mongodb://auth-mongo-srv:27017/auth"
#            - name: JWT_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: jwt-secret
#                  key: JWT_KEY
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: auth-srv
#spec:
#  selector:
#    app: auth
#  ports:
#    - name: auth
#      protocol: TCP
#      port: 3000
#      targetPort: 3000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: registry.digitalocean.com/easymez/auth
          env:
            - name: MONGO_URI
              value: "mongodb+srv://kursat:kursat@easymez.fb8z5.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: backend
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
