name: deploy-facebook-webhook

on:
  push:
    branches:
      - master
    paths:
      - 'facebook-webhook/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd facebookwebhook && docker build -t kursat38tr/facebookwebhook .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push kursat38tr/facebookwebhook
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save easymez
      - run: kubectl rollout restart -n backend deployment facebookwebhook
        #dasd
