name: tests-facebookwebhook

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd facebook-webhook && npm install && npm run test:ci
